version: "3"

services:
  app:
    image: "snuffydev/alphatrack:master"
    build:
      context: ./app
      dockerfile: Dockerfile
      args:
        - PORT=$PORT
    ports:
      - "443:${PORT}"
    environment:
      PORT: 3000
      VITE_DOMAIN: "alphatrack.alphainfinity3.com"
      VITE_SITE_URL: "https://alphatrack.alphainfinity3.com"
      VITE_DONATION_URL: "https:/alphatracks.alphainfinity3.com/donate"
    restart: unless-stopped
  proxy:
    build:
      context: ./packages/proxy-server/deno
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    restart: unless-stopped
